2022.09.30 13:20:34 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 13:20:34 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 13:20:34 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 13:20:34 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 13:20:34 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 13:20:34 LOG5[ui]: FIPS mode disabled
2022.09.30 13:20:34 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 13:20:34 LOG5[ui]: Configuration successful
2022.09.30 13:20:34 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 13:24:41 LOG5[ui]: Terminated
2022.09.30 13:24:50 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 13:24:50 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 13:24:50 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 13:24:50 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 13:24:50 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 13:24:50 LOG5[ui]: FIPS mode disabled
2022.09.30 13:24:50 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 13:24:50 LOG5[ui]: Configuration successful
2022.09.30 13:24:50 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:09:50 LOG5[ui]: Terminated
2022.09.30 14:10:04 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:10:04 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:10:04 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:10:04 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:10:04 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:10:04 LOG5[ui]: FIPS mode disabled
2022.09.30 14:10:04 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:10:04 LOG5[ui]: Configuration successful
2022.09.30 14:10:04 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:10:19 LOG3[ui]: Received SIGINT; terminating
2022.09.30 14:12:15 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:12:15 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:12:15 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:12:15 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:12:15 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:12:15 LOG5[ui]: FIPS mode disabled
2022.09.30 14:12:15 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:12:15 LOG5[ui]: Configuration successful
2022.09.30 14:12:15 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:13:03 LOG5[0]: Service [https] accepted connection from 192.168.84.50:51970
2022.09.30 14:13:03 LOG3[0]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:13:03 LOG5[1]: Service [https] accepted connection from 192.168.84.50:51972
2022.09.30 14:13:03 LOG3[1]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:13:03 LOG5[2]: Service [https] accepted connection from 192.168.84.50:51982
2022.09.30 14:13:03 LOG3[2]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:13:03 LOG5[3]: Service [https] accepted connection from 192.168.84.50:51994
2022.09.30 14:13:03 LOG3[3]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:13:03 LOG5[5]: Service [https] accepted connection from 192.168.84.50:52006
2022.09.30 14:13:03 LOG3[5]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:13:03 LOG5[4]: Service [https] accepted connection from 192.168.84.50:51996
2022.09.30 14:13:03 LOG3[4]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:13:03 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[6]: Service [https] accepted connection from 192.168.84.50:38962
2022.09.30 14:15:20 LOG3[6]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[7]: Service [https] accepted connection from 192.168.84.50:38978
2022.09.30 14:15:20 LOG3[7]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[8]: Service [https] accepted connection from 192.168.84.50:38984
2022.09.30 14:15:20 LOG3[8]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[9]: Service [https] accepted connection from 192.168.84.50:38990
2022.09.30 14:15:20 LOG3[9]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[10]: Service [https] accepted connection from 192.168.84.50:38996
2022.09.30 14:15:20 LOG5[11]: Service [https] accepted connection from 192.168.84.50:39010
2022.09.30 14:15:20 LOG3[10]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[12]: Service [https] accepted connection from 192.168.84.50:39014
2022.09.30 14:15:20 LOG3[12]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG3[11]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:20 LOG5[13]: Service [https] accepted connection from 192.168.84.50:39028
2022.09.30 14:15:20 LOG3[13]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:20 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:46 LOG5[14]: Service [https] accepted connection from 192.168.84.50:58558
2022.09.30 14:15:46 LOG3[14]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:46 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:46 LOG5[15]: Service [https] accepted connection from 192.168.84.50:58564
2022.09.30 14:15:46 LOG5[16]: Service [https] accepted connection from 192.168.84.50:58574
2022.09.30 14:15:46 LOG3[15]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:46 LOG3[16]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:46 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:46 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:15:46 LOG5[17]: Service [https] accepted connection from 192.168.84.50:58576
2022.09.30 14:15:46 LOG3[17]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:15:46 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:17:10 LOG5[18]: Service [https] accepted connection from 192.168.84.50:55406
2022.09.30 14:17:10 LOG3[18]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:17:10 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:17:10 LOG5[19]: Service [https] accepted connection from 192.168.84.50:55408
2022.09.30 14:17:10 LOG5[20]: Service [https] accepted connection from 192.168.84.50:55416
2022.09.30 14:17:10 LOG3[20]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:17:10 LOG3[19]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:17:10 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:17:10 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:17:10 LOG5[21]: Service [https] accepted connection from 192.168.84.50:55432
2022.09.30 14:17:10 LOG3[21]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:17:10 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:17:56 LOG5[ui]: Terminated
2022.09.30 14:17:59 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:17:59 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:17:59 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:17:59 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:17:59 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:17:59 LOG5[ui]: FIPS mode disabled
2022.09.30 14:17:59 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:17:59 LOG5[ui]: Configuration successful
2022.09.30 14:17:59 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:18:10 LOG5[0]: Service [https] accepted connection from 192.168.84.50:56426
2022.09.30 14:18:10 LOG5[1]: Service [https] accepted connection from 192.168.84.50:56442
2022.09.30 14:18:10 LOG3[0]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:18:10 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:18:10 LOG3[1]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:18:10 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:22:06 LOG5[ui]: Terminated
2022.09.30 14:23:58 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:23:58 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:23:58 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:23:58 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:23:58 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:23:58 LOG5[ui]: FIPS mode disabled
2022.09.30 14:23:58 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:23:58 LOG5[ui]: Configuration successful
2022.09.30 14:23:58 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:24:06 LOG5[0]: Service [https] accepted connection from 192.168.84.50:39372
2022.09.30 14:24:06 LOG3[0]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:24:06 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:24:06 LOG5[1]: Service [https] accepted connection from 192.168.84.50:39380
2022.09.30 14:24:06 LOG5[2]: Service [https] accepted connection from 192.168.84.50:39384
2022.09.30 14:24:06 LOG3[1]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:24:06 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:24:06 LOG3[2]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:24:06 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:25:48 LOG5[ui]: Terminated
2022.09.30 14:25:50 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:25:50 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:25:50 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:25:50 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:25:50 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:25:50 LOG5[ui]: FIPS mode disabled
2022.09.30 14:25:50 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:25:50 LOG5[ui]: Configuration successful
2022.09.30 14:25:50 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:25:59 LOG5[0]: Service [https] accepted connection from 192.168.84.50:52474
2022.09.30 14:25:59 LOG3[0]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:25:59 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:25:59 LOG5[1]: Service [https] accepted connection from 192.168.84.50:52488
2022.09.30 14:25:59 LOG5[2]: Service [https] accepted connection from 192.168.84.50:52500
2022.09.30 14:25:59 LOG3[1]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:25:59 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:25:59 LOG3[2]: SSL_accept: ssl/record/rec_layer_s3.c:1543: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2022.09.30 14:25:59 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:26 LOG5[ui]: Terminated
2022.09.30 14:46:35 LOG5[ui]: stunnel 5.65 on x86_64-pc-linux-gnu platform
2022.09.30 14:46:35 LOG5[ui]: Compiled/running with OpenSSL 1.1.1q  5 Jul 2022
2022.09.30 14:46:35 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,OCSP,PSK,SNI
2022.09.30 14:46:35 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 14:46:35 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 14:46:35 LOG5[ui]: FIPS mode disabled
2022.09.30 14:46:35 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 14:46:35 LOG5[ui]: Configuration successful
2022.09.30 14:46:35 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.09.30 14:46:58 LOG5[0]: Service [https] accepted connection from 127.0.0.1:44118
2022.09.30 14:46:58 LOG3[0]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:58 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:58 LOG5[1]: Service [https] accepted connection from 127.0.0.1:44128
2022.09.30 14:46:58 LOG3[1]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:58 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:58 LOG5[2]: Service [https] accepted connection from 127.0.0.1:44140
2022.09.30 14:46:58 LOG5[3]: Service [https] accepted connection from 127.0.0.1:44150
2022.09.30 14:46:58 LOG3[2]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:58 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:58 LOG3[3]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:58 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:59 LOG5[4]: Service [https] accepted connection from 127.0.0.1:44160
2022.09.30 14:46:59 LOG3[4]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:59 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:59 LOG5[5]: Service [https] accepted connection from 127.0.0.1:44162
2022.09.30 14:46:59 LOG3[5]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:59 LOG5[6]: Service [https] accepted connection from 127.0.0.1:44170
2022.09.30 14:46:59 LOG5[5]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:46:59 LOG3[6]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:46:59 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:04 LOG5[7]: Service [https] accepted connection from 127.0.0.1:44172
2022.09.30 14:47:04 LOG3[7]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:04 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:04 LOG5[8]: Service [https] accepted connection from 127.0.0.1:44178
2022.09.30 14:47:04 LOG3[8]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:04 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:04 LOG5[9]: Service [https] accepted connection from 127.0.0.1:44186
2022.09.30 14:47:04 LOG5[10]: Service [https] accepted connection from 127.0.0.1:44198
2022.09.30 14:47:04 LOG3[9]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:04 LOG3[10]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:04 LOG5[9]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:04 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[11]: Service [https] accepted connection from 127.0.0.1:44210
2022.09.30 14:47:06 LOG3[11]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[12]: Service [https] accepted connection from 127.0.0.1:44222
2022.09.30 14:47:06 LOG3[12]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[13]: Service [https] accepted connection from 127.0.0.1:44234
2022.09.30 14:47:06 LOG3[13]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[14]: Service [https] accepted connection from 127.0.0.1:44240
2022.09.30 14:47:06 LOG3[14]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[15]: Service [https] accepted connection from 127.0.0.1:44254
2022.09.30 14:47:06 LOG5[16]: Service [https] accepted connection from 127.0.0.1:44270
2022.09.30 14:47:06 LOG3[16]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG3[15]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[15]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[17]: Service [https] accepted connection from 127.0.0.1:44276
2022.09.30 14:47:06 LOG3[17]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:06 LOG5[18]: Service [https] accepted connection from 127.0.0.1:44280
2022.09.30 14:47:06 LOG3[18]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:06 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG5[19]: Service [https] accepted connection from 127.0.0.1:43528
2022.09.30 14:47:09 LOG3[19]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG5[20]: Service [https] accepted connection from 127.0.0.1:43538
2022.09.30 14:47:09 LOG3[20]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG5[22]: Service [https] accepted connection from 127.0.0.1:43550
2022.09.30 14:47:09 LOG5[21]: Service [https] accepted connection from 127.0.0.1:43548
2022.09.30 14:47:09 LOG3[22]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[22]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG3[21]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG5[23]: Service [https] accepted connection from 127.0.0.1:43558
2022.09.30 14:47:09 LOG3[23]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:09 LOG5[24]: Service [https] accepted connection from 127.0.0.1:43564
2022.09.30 14:47:09 LOG3[24]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:09 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[25]: Service [https] accepted connection from 127.0.0.1:54888
2022.09.30 14:47:20 LOG3[25]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[26]: Service [https] accepted connection from 127.0.0.1:54890
2022.09.30 14:47:20 LOG3[26]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[26]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[27]: Service [https] accepted connection from 127.0.0.1:54894
2022.09.30 14:47:20 LOG3[27]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[28]: Service [https] accepted connection from 127.0.0.1:54908
2022.09.30 14:47:20 LOG3[28]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[30]: Service [https] accepted connection from 127.0.0.1:54920
2022.09.30 14:47:20 LOG5[29]: Service [https] accepted connection from 127.0.0.1:54914
2022.09.30 14:47:20 LOG3[30]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG3[29]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[32]: Service [https] accepted connection from 127.0.0.1:54948
2022.09.30 14:47:20 LOG5[31]: Service [https] accepted connection from 127.0.0.1:54936
2022.09.30 14:47:20 LOG3[31]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG3[32]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:20 LOG5[31]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:20 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:32 LOG5[34]: Service [https] accepted connection from 127.0.0.1:59920
2022.09.30 14:47:32 LOG5[33]: Service [https] accepted connection from 127.0.0.1:59918
2022.09.30 14:47:32 LOG3[33]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:32 LOG3[34]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:32 LOG5[33]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:32 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:32 LOG5[35]: Service [https] accepted connection from 127.0.0.1:59928
2022.09.30 14:47:32 LOG3[35]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:32 LOG5[35]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:32 LOG5[36]: Service [https] accepted connection from 127.0.0.1:59944
2022.09.30 14:47:32 LOG3[36]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:32 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[37]: Service [https] accepted connection from 127.0.0.1:57112
2022.09.30 14:47:57 LOG3[37]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[37]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[38]: Service [https] accepted connection from 127.0.0.1:57126
2022.09.30 14:47:57 LOG3[38]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[38]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[39]: Service [https] accepted connection from 127.0.0.1:57142
2022.09.30 14:47:57 LOG3[39]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[40]: Service [https] accepted connection from 127.0.0.1:57150
2022.09.30 14:47:57 LOG3[40]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[40]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[41]: Service [https] accepted connection from 127.0.0.1:57154
2022.09.30 14:47:57 LOG3[41]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[42]: Service [https] accepted connection from 127.0.0.1:57156
2022.09.30 14:47:57 LOG5[41]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG3[42]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[42]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG5[44]: Service [https] accepted connection from 127.0.0.1:57172
2022.09.30 14:47:57 LOG5[43]: Service [https] accepted connection from 127.0.0.1:57162
2022.09.30 14:47:57 LOG3[43]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[43]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:47:57 LOG3[44]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:47:57 LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[45]: Service [https] accepted connection from 127.0.0.1:50172
2022.09.30 14:48:20 LOG3[45]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[45]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[46]: Service [https] accepted connection from 127.0.0.1:50178
2022.09.30 14:48:20 LOG3[46]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[46]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[47]: Service [https] accepted connection from 127.0.0.1:50182
2022.09.30 14:48:20 LOG3[47]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[47]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[48]: Service [https] accepted connection from 127.0.0.1:50198
2022.09.30 14:48:20 LOG3[48]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[49]: Service [https] accepted connection from 127.0.0.1:50208
2022.09.30 14:48:20 LOG5[50]: Service [https] accepted connection from 127.0.0.1:50224
2022.09.30 14:48:20 LOG3[49]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[49]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG3[50]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[50]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:20 LOG5[51]: Service [https] accepted connection from 127.0.0.1:50232
2022.09.30 14:48:20 LOG3[51]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:20 LOG5[51]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[52]: Service [https] accepted connection from 127.0.0.1:50246
2022.09.30 14:48:22 LOG3[52]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[52]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[53]: Service [https] accepted connection from 127.0.0.1:50260
2022.09.30 14:48:22 LOG3[53]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[53]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[54]: Service [https] accepted connection from 127.0.0.1:50276
2022.09.30 14:48:22 LOG3[54]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[54]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[55]: Service [https] accepted connection from 127.0.0.1:50278
2022.09.30 14:48:22 LOG3[55]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[55]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[56]: Service [https] accepted connection from 127.0.0.1:50286
2022.09.30 14:48:22 LOG5[57]: Service [https] accepted connection from 127.0.0.1:50288
2022.09.30 14:48:22 LOG3[56]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[56]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG3[57]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[57]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG5[58]: Service [https] accepted connection from 127.0.0.1:50294
2022.09.30 14:48:22 LOG5[59]: Service [https] accepted connection from 127.0.0.1:50306
2022.09.30 14:48:22 LOG3[58]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[58]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:22 LOG3[59]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:22 LOG5[59]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG5[60]: Service [https] accepted connection from 127.0.0.1:50316
2022.09.30 14:48:23 LOG3[60]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[60]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG5[61]: Service [https] accepted connection from 127.0.0.1:50324
2022.09.30 14:48:23 LOG3[61]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[61]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG5[62]: Service [https] accepted connection from 127.0.0.1:50340
2022.09.30 14:48:23 LOG5[63]: Service [https] accepted connection from 127.0.0.1:50346
2022.09.30 14:48:23 LOG3[62]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[62]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG3[63]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[63]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG5[65]: Service [https] accepted connection from 127.0.0.1:50368
2022.09.30 14:48:23 LOG5[64]: Service [https] accepted connection from 127.0.0.1:50362
2022.09.30 14:48:23 LOG3[65]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[65]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:23 LOG3[64]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:23 LOG5[64]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[66]: Service [https] accepted connection from 127.0.0.1:50382
2022.09.30 14:48:27 LOG3[66]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[66]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[67]: Service [https] accepted connection from 127.0.0.1:50398
2022.09.30 14:48:27 LOG3[67]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[67]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[68]: Service [https] accepted connection from 127.0.0.1:50410
2022.09.30 14:48:27 LOG3[68]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[68]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[69]: Service [https] accepted connection from 127.0.0.1:50418
2022.09.30 14:48:27 LOG3[69]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[69]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[70]: Service [https] accepted connection from 127.0.0.1:50428
2022.09.30 14:48:27 LOG5[71]: Service [https] accepted connection from 127.0.0.1:50432
2022.09.30 14:48:27 LOG3[70]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG3[71]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[70]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[71]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG5[72]: Service [https] accepted connection from 127.0.0.1:50438
2022.09.30 14:48:27 LOG3[72]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[73]: Service [https] accepted connection from 127.0.0.1:50450
2022.09.30 14:48:27 LOG5[72]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:27 LOG3[73]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:27 LOG5[73]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[74]: Service [https] accepted connection from 127.0.0.1:50464
2022.09.30 14:48:28 LOG3[74]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[74]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[75]: Service [https] accepted connection from 127.0.0.1:50470
2022.09.30 14:48:28 LOG3[75]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[75]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[76]: Service [https] accepted connection from 127.0.0.1:50482
2022.09.30 14:48:28 LOG3[76]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[76]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[77]: Service [https] accepted connection from 127.0.0.1:50496
2022.09.30 14:48:28 LOG3[77]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[77]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[79]: Service [https] accepted connection from 127.0.0.1:50510
2022.09.30 14:48:28 LOG5[78]: Service [https] accepted connection from 127.0.0.1:50504
2022.09.30 14:48:28 LOG3[79]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG3[78]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[79]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[78]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:28 LOG5[80]: Service [https] accepted connection from 127.0.0.1:50520
2022.09.30 14:48:28 LOG3[80]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:28 LOG5[80]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[81]: Service [https] accepted connection from 127.0.0.1:60792
2022.09.30 14:48:50 LOG3[81]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[81]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[82]: Service [https] accepted connection from 127.0.0.1:60800
2022.09.30 14:48:50 LOG3[82]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[82]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[83]: Service [https] accepted connection from 127.0.0.1:60816
2022.09.30 14:48:50 LOG3[83]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[83]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[84]: Service [https] accepted connection from 127.0.0.1:60828
2022.09.30 14:48:50 LOG3[84]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[84]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[85]: Service [https] accepted connection from 127.0.0.1:60832
2022.09.30 14:48:50 LOG3[85]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[85]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[87]: Service [https] accepted connection from 127.0.0.1:60850
2022.09.30 14:48:50 LOG5[86]: Service [https] accepted connection from 127.0.0.1:60836
2022.09.30 14:48:50 LOG3[87]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[87]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG3[86]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[86]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 14:48:50 LOG5[88]: Service [https] accepted connection from 127.0.0.1:60866
2022.09.30 14:48:50 LOG3[88]: SSL_accept: ssl/statem/statem_lib.c:109: error:141FC044:SSL routines:tls_setup_handshake:internal error
2022.09.30 14:48:50 LOG5[88]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2022.09.30 16:31:07 LOG5[ui]: Reading configuration from file /home/starlab/Documents/withsql/stunnel/dev_https
2022.09.30 16:31:07 LOG5[ui]: UTF-8 byte order mark not detected
2022.09.30 16:31:07 LOG5[ui]: FIPS mode disabled
2022.09.30 16:31:07 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2022.09.30 16:31:07 LOG5[ui]: Configuration successful
2022.09.30 16:31:07 LOG5[ui]: Binding service [https] to :::8443: Address already in use (98)
2022.10.01 14:46:35 LOG5[ui]: Log file reopened
2022.10.02 14:46:35 LOG5[ui]: Log file reopened
2022.10.03 08:30:06 LOG5[ui]: Terminated
